### ISSUE TITLE
Babel parse error with markdown code blocks

### ISSUE THREAD

**Issue by fasetto** [hashicorp/next-mdx-remote#114]
```term
SyntaxError: unknown: Unexpected reserved word 'private' (100:4)

   98 | ```cs
   99 | {
> 100 |     private readonly TruckerDbContext _dbContext;
      |     ^
  101 | <pre><code parentName="pre" {...{}}>{`public TruckRepository(TruckerDbContext dbContext) :
  102 |     base(dbContext)
  103 | {
    at Object._raise (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:775:17)
    at Object.raiseWithData (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:768:17)
    at Object.raise (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:736:17)
    at Object.checkReservedWord (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:11903:12)
    at Object.parseIdentifierName (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:11865:12)
    at Object.parseIdentifier (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:11832:23)
    at Object.parseExprAtom (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10924:27)
    at Object.parseExprAtom (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:5173:20)
    at Object.parseExprSubscripts (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10668:23)
    at Object.parseUpdate (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10648:21)
    at Object.parseMaybeUnary (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10626:23)
    at Object.parseExprOps (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10487:23)
    at Object.parseMaybeConditional (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10461:23)
    at Object.parseMaybeAssign (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10424:21)
    at Object.parseExpressionBase (C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10369:23)
    at C:\Users\serka\Source\Repos\personal-site\node_modules\@babel\parser\lib\index.js:10363:39 {
  loc: Position { line: 100, column: 4 },
  pos: 25381,
  code: 'BABEL_PARSE_ERROR'
}
```

Any idea why I am getting this error, how to fix it ?

**Comment by BRKalow** [comment]
Thanks for the report! Would you be able to provide a minimal reproduction? A repo or a [CodeSandbox](https://codesandbox.io/) are great options.

This would make it much easier for us to troubleshoot. 🙏

**Comment by fasetto** [comment]
Right. It is my first time using mdx, I don't know if this is a bug, most likely my fault. 
I'll share the repo when I finish the changes.

**Comment by fasetto** [comment]
@BRKalow 
[Here](https://github.com/fasetto/personal-site/tree/dev) is the repo. I have an mdx file in the `dev` branch under the `/data/blog` dir. It has lot of code blocks.

Here is the steps to reproduce the issue;
- Start the Next JS app with `yarn dev`
- Go to the `localhost:3000/blog/repository-pattern-ve-tipik-hatalar`
Then you will see the issue. 🙂

**Comment by fasetto** [comment]
I solved this btw. Putting `<br />` *(or any valid html tag)* before the code blocks causes parsing issues. It needs some space I think, I've put the new line after it to seperate and it worked.
Not related to `next-mdx-remote`, closing this.
