### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rodbs** [hashicorp/next-mdx-remote#13]
I'm replicating the example you've posted in my project 

```
export async function getStaticProps() {
  const { posts } = await getAllPosts();
  //   console.log(posts);
  const source = 'Some **mdx** text, with a component  ';
  const mdxSource = await renderToString(source, components);
  return {
    props: {
      posts,
      mdxSource
    },
    unstable_revalidate: 1
  };
}
```

I've tried  different ways but I'm always getting this error. Any ideas? is it a bug?
![image](https://user-images.githubusercontent.com/4244067/87579708-a44c8280-c6d6-11ea-9ff1-b3011818fc5d.png)

  ```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at C:\igls\igls-next-firebase\node_modules\next-mdx-remote\render-to-string.js:43:19   
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getStaticProps (C:\igls\igls-next-firebase\.next\server\static\development\pages\blog.js:2048:21)
    at async renderToHTML (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\render.js:27:109)
    at async C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:68:285
    at async __wrapper (C:\igls\igls-next-firebase\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:91:254)
    at async DevServer.renderToHTML (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:92:254)
    at async DevServer.renderToHTML (C:\igls\igls-next-firebase\node_modules\next\dist\server\next-dev-server.js:22:539)
    at async DevServer.render (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:48:236)
    at async Object.fn (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:35:852)
    at async Router.execute (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\router.js:28:28)
    at async DevServer.run (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:44:494)
    at async DevServer.handleRequest (C:\igls\igls-next-firebase\node_modules\next\dist\next-server\server\next-server.js:13:133)

```

**Comment by jescalan** [comment]
It looks like `components` is undefined, no?

**Comment by rodbs** [comment]
> 
> 
> It looks like `components` is undefined, no?

`components` is defined, it's out of the `getStaticProps` function. I've tried to move it inside and I get the same error.
I've also tried to just remove `components` from `renderToString` and I also get the same error

**Comment by rodbs** [comment]
I also get this message when importing, but it doesn't seem an error:

![image](https://user-images.githubusercontent.com/4244067/87693482-56468600-c78d-11ea-851b-1d766daf558c.png)

**Comment by jescalan** [comment]
@rodbs - this is not a bug with `next-mdx-remote`, it is user error. i am happy to try to help, but what you need to do is produce a *minimal reproduction*, make a repo for it, and link me to the repo. That means trimming down everything else in your app until you get only to the minimum amount of code you can use to produce the error.

As for the second issue, this is a typescript warning. This library does not export types for typescript. If anyone would like to add typescript types, they are more than welcome to do so via pull request!

**Comment by rodbs** [comment]
@jescalan 
Here you have the repo.
https://github.com/rodbs/nextjs-mdx-remote

It's a clean nextjs project with next-mdx-remote added
I've created two pages, one directly copied from the TestPage example it's on this repo front-page
I'm always getting the same error.
Thanks!

**Comment by jescalan** [comment]
Thank you so much for the reproduction, this was enormously helpful in isolating what did end up being a bug. I just put out a patch that fixes it - upgrading the version should resolve the problem!

**Comment by rodbs** [comment]
@jescalan 
Yes, it works now. Thanks!
