### ISSUE TITLE
JSON embedded in content should not be parsed as JSON

### ISSUE THREAD

**Issue by lorenzode** [hashicorp/next-mdx-remote#225]
I have next-mdx-remote working for my NextJs application.

However when I use JSON examples like `'<p><code>\"data\": [{object}, {object}, {object}…]</code></p>\n'` in my content, I get this error:

`ReferenceError: object is not defined`

```
index.js?46cb:323 Uncaught     at MDXContent (file:///[PATH]/node_modules/next-mdx-remote/dist/index.js:83:35)
    at processChild (file:///[PATH]/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (file:///[PATH]/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (file:///[PATH]/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (file:///[PATH]/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (file:///[PATH]/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at renderPage (file:///[PATH]/node_modules/next/dist/server/render.js:723:46)
    at Object.ctx.renderPage (webpack-internal:///./pages/_document.tsx:16:20)
    at Object.defaultGetInitialProps (file:///[PATH]/node_modules/next/dist/server/render.js:364:51)
    at Function.getInitialProps (webpack-internal:///./node_modules/next/dist/pages/_document.js:142:20)
```

Versions:
- "next": "^12.0.8",
-  "next-mdx-remote": "^3.0.8",
-  "react": "^17.0.2",

```
// /pages/[locale]/[category]/[slug].tsx

import { serialize } from 'next-mdx-remote/serialize'

...

// getStaticProps
const serializedContents = await serialize(
 // All content works fine except this bit doesn't work:
  '<p><code>\"data\": [{object}, {object}, {object}…]</code></p>\n'
)
```
I tried this but it doesn't work either

```
const serializedContents = await serialize(
 '&quot;data&quot;&#58; &#91;&#123;object&#125;, &#123;object&#125;, &#123;object&#125;…&#93;
)
```

This is working however (removing the `{` around `object`):

```
const serializedContents = await serialize(
    '<p><code>\"data\": [object, object, object…]</code></p>\n'
)
```

This is the React component rendering the page:

```
export const Page: React.FC<{
  page: APIData,
  serializedContents: any
}>  = (props) => {
  const {page, serializedContents} = props

  return (
    <div>
      <h1>{page.title}</h1>
      <article>
        <MDXRemote {...serializedContents} components={widgets} />
      </article>
    </div>
  )
}
```
Again, everything is working fine for HTML tags in my content etc, only JSON examples in my article fail to render.

Why is JSON embedded in `<code>` making next-remote-mdx fail?

**Comment by lorenzode** [comment]
For completeness, here is _document.tsx:

```
import Document, { DocumentContext, Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    let pageProps = null

    const originalRenderPage = ctx.renderPage

    ctx.renderPage = () =>
      originalRenderPage({
        enhanceApp: (App) => (props) => {
          pageProps = props?.pageProps
          return <App {...props} />
        },
        enhanceComponent: (Component) => Component,
      })

    const initialProps = await Document.getInitialProps(ctx)
    return { ...initialProps, pageProps }
  }

  render() {
    const { pageProps } = (this.props as any)
    return (
      <Html lang={
        pageProps && pageProps[Object.keys(pageProps)[0]]
          ? pageProps[Object.keys(pageProps)[0]].locale
          : 'en'
      }>
        <Head>
          <script async src="/analytics.js" />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument
```

**Comment by BRKalow** [comment]
This is invalid MDX. You could try wrapping the JSON in a markdown code fence:

<pre>
```
"data": [{object}, {object}, {object}…]
```
</pre>

**Comment by lorenzode** [comment]
@BRKalow thanks but I am doing this already:

This is what we are doing:

1. content editors are code fencing their code examples in Markdown using ` ``` `
2. our system transforms Markdown into HTML, so the code fencing becomes `<code></code>` 
3. Which leaves me with the following markup on the frontend which fails: `<code>\"data\": [{object}, {object}, {object}…]\n</code>`

**Comment by lorenzode** [comment]
... and consuming Markdown code fencing markup also doesn't work by the way:

![Screenshot from 2022-01-20 08-32-48](https://user-images.githubusercontent.com/24975087/150293682-31cdd1e6-bbbc-45f7-a38c-c5768eff7c3d.png)

**Comment by lorenzode** [comment]
Related: https://github.com/hashicorp/next-mdx-remote/issues/83

**Comment by lorenzode** [comment]
I could solve this by using a plugin:

```
  import rehypeHighlight from 'rehype-highlight'

  const serializedContents = await serialize(
    '<p><code>\"data\": [object, object, object…]</code></p>\n',
    {
      mdxOptions: {
        remarkPlugins: [rehypeHighlight]
      }
    }
 )
```

Thank you again @BRKalow
