### ISSUE TITLE
parse failed

### ISSUE THREAD

**Issue by Manonicu** [hashicorp/next-mdx-remote#238]
``` shell
info  - Checking validity of types
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
[    ] info  - Generating static pages (0/102)
Error occurred prerendering page "/blog/javascript/es6/String_Template_Literal". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: expression is not defined
    at _createMdxContent (eval at <anonymous> (file:///Users/pfan/workspaces/github/site/node_modules/.pnpm/next-mdx-remote@4.0.0_react-dom@17.0.2+react@17.0.2/node_modules/next-mdx-remote/dist/index.js:55:35), <anonymous>:32:53)
    at MDXContent (eval at <anonymous> (file:///Users/pfan/workspaces/github/site/node_modules/.pnpm/next-mdx-remote@4.0.0_react-dom@17.0.2+react@17.0.2/node_modules/next-mdx-remote/dist/index.js:55:35), <anonymous>:10:9)
    at d (/Users/pfan/workspaces/github/site/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/Users/pfan/workspaces/github/site/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/pfan/workspaces/github/site/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/pfan/workspaces/github/site/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/Users/pfan/workspaces/github/site/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/Users/pfan/workspaces/github/site/node_modules/.pnpm/next@12.1.0_d4c8e9d0696ef40786054756cfd1867a/node_modules/next/dist/server/render.js:751:45)
    at Object.defaultGetInitialProps (/Users/pfan/workspaces/github/site/node_modules/.pnpm/next@12.1.0_d4c8e9d0696ef40786054756cfd1867a/node_modules/next/dist/server/render.js:389:51)
    at Function.getInitialProps (/Users/pfan/workspaces/github/site/.next/server/chunks/335.js:503:20)
[=   ] info  - Generating static pages (25/102)
Error occurred prerendering page "/blog/swift/100days/day01". Read more: https://nextjs.org/docs/messages/prerender-error
Error: [next-mdx-remote] error compiling MDX:
Unexpected character `、` (U+3001) before name, expected a character that can start a name, such as a letter, `$`, or `_`
```

build failed after upgrade to v4

**Comment by BRKalow** [comment]
Can you share a reproduction so we can debug further? Thanks

**Comment by Manonicu** [comment]
> Can you share a reproduction so we can debug further? Thanks

https://github.com/Manonicu/site

clone && update next-mdx-remote to latest.that's all

**Comment by BRKalow** [comment]
There's an error in this file: https://github.com/Manonicu/site/blob/master/_posts/javascript/es6/String_Template_Literal.mdx

On this line:
```
模板字符串使用反引号 (` `) 来代替普通字符串中的用双引号和单引号。模板字符串可以包含特定语法（${expression}）的占位符。占位符中的表达式和周围的文本会一起传递给一个默认函数，该函数负责将所有的部分连接起来，如果一个模板字符串由表达式开头，则该字符串被称为带标签的模板字符串，该表达式通常是一个函数，它会在模板字符串处理后被调用，在输出最终结果前，你都可以通过该函数来对模板字符串进行操作处理。在模版字符串内使用反引号（`）时，需要在它前面加转义符（\）。
```

Note the `${expression}`, gets evaluated by MDX v2 as a JS expression and so we get an `expression is not defined` error.

Escaping the bracket can fix this:
```
模板字符串使用反引号 (` `) 来代替普通字符串中的用双引号和单引号。模板字符串可以包含特定语法（$\{expression}）的占位符。占位符中的表达式和周围的文本会一起传递给一个默认函数，该函数负责将所有的部分连接起来，如果一个模板字符串由表达式开头，则该字符串被称为带标签的模板字符串，该表达式通常是一个函数，它会在模板字符串处理后被调用，在输出最终结果前，你都可以通过该函数来对模板字符串进行操作处理。在模版字符串内使用反引号（`）时，需要在它前面加转义符（\）。
```

Keep in mind MDX v2 does have breaking changes, see the migration guide for more information: https://mdxjs.com/migrating/v2/#update-mdx-files

**Comment by Manonicu** [comment]
> 

got it.thx
