### ISSUE TITLE
MDX with Preact

### ISSUE THREAD

**Issue by AdisonCavani** [hashicorp/next-mdx-remote#300]
## Summary
I have a problem with ``<MDXRemote/>`` component.
It causes to throw an error.
When I comment out this ^^ component, everything works fine.

I'm using Next.js with [next-plugin-preact](https://www.npmjs.com/package/next-plugin-preact).
[Next.js preact example](https://github.com/vercel/next.js/tree/canary/examples/using-preact)

## How to reproduce?
I created a simple repository - https://github.com/AdisonCavani/mdx-preact-issue
- install dependencies - ``yarn install``
- run dev server - ``yarn dev``
- go to: http://localhost:3000/ssg
- see the issue

Similar issue:
- https://github.com/preactjs/preact/issues/3308

<details>
<summary>Error log: </summary><br>

```
error - Error: Hook can only be invoked from render methods.
    at Object.e.__h (file:///C:/Users/Adison/repos/adison.me/src/node_modules/.pnpm/preact@10.11.0/node_modules/preact/debug/dist/debug.mjs:1:5868)
    at p (file:///C:/Users/Adison/repos/adison.me/src/node_modules/.pnpm/preact@10.11.0/node_modules/preact/hooks/dist/hooks.mjs:1:146)
    at h (file:///C:/Users/Adison/repos/adison.me/src/node_modules/.pnpm/preact@10.11.0/node_modules/preact/hooks/dist/hooks.mjs:1:306)
    at y (file:///C:/Users/Adison/repos/adison.me/src/node_modules/.pnpm/preact@10.11.0/node_modules/preact/hooks/dist/hooks.mjs:1:275)
    at Object.MDXRemote (file:///C:/Users/Adison/repos/adison.me/src/node_modules/.pnpm/next-mdx-remote@4.1.0_dmmjpkrptnkrz2kzqikv5vt4mi/node_modules/next-mdx-remote/dist/index.js:31:51)      
    at C:\Users\Adison\repos\adison.me\src\node_modules\.pnpm\preact-render-to-string@5.2.4_preact@10.11.0\node_modules\preact-render-to-string\dist\commonjs.js:1:6391
    at j (C:\Users\Adison\repos\adison.me\src\node_modules\.pnpm\preact-render-to-string@5.2.4_preact@10.11.0\node_modules\preact-render-to-string\dist\commonjs.js:1:6418)
    at j (C:\Users\Adison\repos\adison.me\src\node_modules\.pnpm\preact-render-to-string@5.2.4_preact@10.11.0\node_modules\preact-render-to-string\dist\commonjs.js:1:7480)
    at j (C:\Users\Adison\repos\adison.me\src\node_modules\.pnpm\preact-render-to-string@5.2.4_preact@10.11.0\node_modules\preact-render-to-string\dist\commonjs.js:1:6493)
    at j (C:\Users\Adison\repos\adison.me\src\node_modules\.pnpm\preact-render-to-string@5.2.4_preact@10.11.0\node_modules\preact-render-to-string\dist\commonjs.js:1:5644) {
  page: '/blog/[slug]'
}
```
</details>

## Why Preact?
It helps me to reduce bundle size. ``Preact`` is a lightweight replacement for ``React``.
Size difference - 5kB vs over 100kB.

**Comment by klausdw** [comment]
I'm looking just now for the same issue. (next-plugin-preact)

My error:

Server Error
TypeError: Cannot read properties of undefined (reading '__H')

h
/node_modules/preact/hooks/dist/hooks.mjs (1:306)
Object.MDXRemote
/node_modules/next-mdx-remote/dist/index.js (31:51)

package.json
"dependencies": {
	"next": "12.2.5",
	"next-mdx-remote": "^4.0.3",
	"next-plugin-preact": "^3.0.7",
	"preact": "^10.10.6",
	"preact-render-to-string": "^5.2.3",
	"react": "npm:@preact/compat@^17.1.1",
	"react-dom": "npm:@preact/compat@^17.1.1",
	"react-ssr-prepass": "npm:preact-ssr-prepass@1.2.0",
}

**Comment by fredericoo** [comment]
Having same issue

**Comment by dstaley** [comment]
Thank you for reporting this issue, but we won't be diagnosing compatibility issues with Preact that don't occur in React.
