### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'default')

### ISSUE THREAD

**Issue by lumenwrites** [hashicorp/next-mdx-remote#326]
I'm trying to use MDXRemote, and I'm getting the following error:

```
index.js?46cb:602 Uncaught TypeError: Cannot read properties of undefined (reading 'default')
    at <unknown> (/Users/ray/projects/GDSchool/website/node_modules/next-mdx-remote/dist/index.js:56:50)
    at Object.useMemo (/Users/ray/projects/GDSchool/website/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5124:19)
    at useMemo (/Users/ray/projects/GDSchool/website/node_modules/react/cjs/react.development.js:1650:21)
    at MDXRemote (/Users/ray/projects/GDSchool/website/node_modules/next-mdx-remote/dist/index.js:43:21)
    at renderWithHooks (/Users/ray/projects/GDSchool/website/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (/Users/ray/projects/GDSchool/website/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5731:15)
    at renderElement (/Users/ray/projects/GDSchool/website/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
...
```

Can you help me figure out what could be causing it, and how to fix it?

**Comment by lumenwrites** [comment]
Sorry, nevermind, my mistake.

This happens when you pass it an undefined variable instead of the source:

```
    <MDXRemote {...product.copy} components={MDXComponents} />
```

In my case, `product.copy` happened to be undefined.

**Comment by dymoo** [comment]
`
            {source && <MDXRemote {...source} />}
`

:)
