### ISSUE TITLE
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. 

### ISSUE THREAD

**Issue by Th3R3p0** [hashicorp/next-mdx-remote#359]
👋 Hey next-mdx-remote devs,

I am running into an issue when running `"next-mdx-remote": "^4.4.1"`. When I downgrade to `3.0.1` (which is the version listed in Vercel's [example code](https://github.com/vercel/next.js/blob/canary/examples/with-mdx-remote/package.json#L12)), it works. 

When I downgrade to `3.0.1`, I receive the warning `found 2 high severity vulnerabilities` when installing the dependencies. 

Should I downgrade to another version? Is there something that I am missing here? 

Below are my stack traces and the package.json files I have tested with. 

Thank you in advance! 🙏 

```
error - file:///Users/me/website/node_modules/next-mdx-remote/dist/index.js:1
import React, { useState, useEffect, useMemo } from 'react';
                                     ^^^^^^^
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const { useState, useEffect, useMemo } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24) {
  page: '/blog/example'
}
error - file:///Users/me/website/node_modules/next-mdx-remote/dist/index.js:1
import React, { useState, useEffect, useMemo } from 'react';
                                     ^^^^^^^
SyntaxError: The requested module 'react' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'react';
const { useState, useEffect, useMemo } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:98:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:137:5)
    at async Loader.import (internal/modules/esm/loader.js:165:24) {
  page: '/blog/example'
}
```

**Failing `package.json` file**
```json
{
  "name": "website",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.12",
    "eslint": "8.35.0",
    "eslint-config-next": "13.2.3",
    "gray-matter": "^4.0.2",
    "next": "latest",
    "next-mdx-remote": "^4.4.1",
    "next-remote-watch": "^2.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "use-exit-intent": "^1.0.7"
  },
  "devDependencies": {
    "@svgr/webpack": "^6.5.1"
  }
}
```

**Working `package.json` file**
```json
{
  "name": "website",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mui/icons-material": "^5.11.11",
    "@mui/material": "^5.11.12",
    "eslint": "8.35.0",
    "eslint-config-next": "13.2.3",
    "gray-matter": "^4.0.2",
    "next": "latest",
    "next-mdx-remote": "^3.0.1",
    "next-remote-watch": "^1.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "use-exit-intent": "^1.0.7"
  },
  "devDependencies": {
    "@svgr/webpack": "^6.5.1"
  }
}
```

**Comment by dstaley** [comment]
If you can provide a minimal reproduction I'd be happy to look into this for you, but it looks like this might have been run on a version of Node that didn't allow ESM imports of CommonJS modules. If this happens on Node v18 (or higher) please let me know!
