### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by dprothero** [hashicorp/next-mdx-remote#372]
I'm trying to use MDXRemote using the classic pages router and am getting the following error:

```
- error TypeError: Cannot read properties of null (reading 'useState')
    at useState (/Users/dprothero/Projects/docs2/node_modules/react/cjs/react.development.js:1622:21)
    at MDXRemote (file:///Users/dprothero/Projects/docs2/node_modules/next-mdx-remote/dist/index.js:40:51)
[snipped]
```

It works if we use create-next-app, but we get this error when using nx with @nx/next to generate a next.js project.

Reproduced on [this codesandbox](https://codesandbox.io/p/github/dprothero/mdx-remote-error/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cli2xef9p000a3t6kvei2ql01%2522%253A%257B%2522id%2522%253A%2522cli2xef9p000a3t6kvei2ql01%2522%252C%2522activeTabId%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cli2xef9p00093t6k2iplb59y%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cli2xg7pz00qm3t6kt0sxip5d%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cli2xn2t5000a3t6kze7ukk93%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522npx%2520nx%2520serve%2520twilio-cli%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522cli2xntl200mf3t6k92vd4ogk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252Fdocs%252Ftwilio-cli%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D):

1. Define the starting process: `npx nx serve twilio-cli`
2. Try to load the `/docs/twilio-cli` route.

**Comment by BRKalow** [comment]
Hey there, thanks for the reproduction. It looks like there are multiple copies of react being loaded here. I'm not super familiar with how nx works, but it looks like it's potentially an interaction with how nx handles dependencies and next aliasing to its internal copy of react.

Potentially related: https://github.com/vercel/next.js/issues/50158

**Comment by dprothero** [comment]
Downgrading to Next 13.2.4 is a workaround for the problem, so something in Next changed that's incompatible with how Nx does things.

**Comment by karlhorky** [comment]
For our app, it had two similar errors (erroring on `useContext` and `useRef`):

```bash
$ next build
   ▲ Next.js 14.1.0
   - Environments: .env.production
   - Experiments (use at your own risk):
     · typedRoutes

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data    
   Generating static pages (0/9)  [=   ]TypeError: Cannot read properties of null (reading 'useContext')
    at exports.useContext (/Users/k/p/project/packages/package/node_modules/react/cjs/react.production.min.js:24:118)
    at h (/Users/k/p/project/packages/package/.next/server/pages/_error.js:1:6023)
    at Wc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at $c (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:71:145)

Error occurred prerendering page "/404". Read more: https://nextjs.org/docs/messages/prerender-error
```

After upgrading to Next.js canary version:

```bash
$ next build
   ▲ Next.js 14.1.1-canary.67
   - Environments: .env.production
   - Experiments (use with caution):
     · typedRoutes

   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping validation of types
   Skipping linting
 ✓ Collecting page data    
   Generating static pages (0/9)  [=   ]TypeError: Cannot read properties of null (reading 'useRef')
    at exports.useRef (/Users/k/p/project/packages/package/node_modules/react/cjs/react.production.min.js:25:337)
    at eB (/Users/k/p/project/packages/package/node_modules/next/dist/compiled/next-server/pages.runtime.prod.js:16:19551)
    at Wc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at Zc (/Users/k/p/project/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)

Error occurred prerendering page "/500". Read more: https://nextjs.org/docs/messages/prerender-error
```

## Resolution

Removing our [Yarn Workspaces `nohoist` config](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) fixed this:

```js
{
  "name": "monorepo",
  "version": "1.0.0",
  "private": true,
  "workspaces": {
    "packages": [
      "packages/*",
    ],
    "nohoist": [
      "**/next-mdx-remote", // 💥 This was the line that was causing it to fail for us
    ]
  }
}
```

This leads me to believe it was indeed related to our Yarn workspaces monorepo setup, and multiple copies of React being loaded.
