### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by lumenwrites** [hashicorp/next-mdx-remote#381]
I'm trying to complie mdx like this:
```
import { serialize } from 'next-mdx-remote/serialize'
import matter from 'gray-matter'

export async function renderMDX(text) {
  const { data: frontmatter, content } = matter(text)
  const serialized = await serialize(content, {
    scope: frontmatter,
  })
  return serialized
}
```
I run this script with typescript, and I get the following error:
```
/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:851
            return old(m, filename);
                   ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/lumen/projects/Webdev/obsidian-blog/node_modules/next-mdx-remote/serialize.js from /Users/lumen/projects/Webdev/obsidian-blog/content/render-mdx.ts not supported.
Instead change the require of serialize.js in /Users/lumen/projects/Webdev/obsidian-blog/content/render-mdx.ts to a dynamic import() which is available in all CommonJS modules.
    at require.extensions.<computed> [as .js] (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:851:20)
    at Object.<anonymous> (/Users/lumen/projects/Webdev/obsidian-blog/content/render-mdx.ts:7:21)
    at m._compile (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/lumen/projects/Webdev/obsidian-blog/content/process-posts.ts:10:22)
    at m._compile (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:859:16)
    at Object.<anonymous> (/Users/lumen/projects/Webdev/obsidian-blog/content/process-content.ts:8:25)
    at m._compile (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:857:29)
    at require.extensions.<computed> [as .ts] (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/index.js:859:16)
    at phase4 (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/bin.js:466:20)
    at bootstrap (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/bin.js:54:12)
    at main (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/bin.js:33:12)
    at Object.<anonymous> (/Users/lumen/projects/Webdev/obsidian-blog/node_modules/ts-node/dist/bin.js:579:5) {
  code: 'ERR_REQUIRE_ESM'
}
```

Do you know what I could do to fix it?

**Comment by lumenwrites** [comment]
Small script reproducing the error:
https://github.com/lumenwrites/next-mdx-remote-import-issue/blob/main/src/index.ts

**Comment by talatkuyuk** [comment]
Hi @lumenwrites, did you find a solution?

**Comment by SuperchupuDev** [comment]
Getting this problem after updating to next 14.2

**Comment by dstaley** [comment]
@SuperchupuDev can you try with `next-mdx-remote@0.0.0-canary-20240321205249` and let me know if you're still experiencing this issue?

**Comment by SuperchupuDev** [comment]
@dstaley Still getting the same error

![image](https://github.com/hashicorp/next-mdx-remote/assets/53496941/45101921-52e0-4d65-aa2a-2964999f0ef5)

**Comment by SuperchupuDev** [comment]
Using `next dev --turbo` warns that this package is invalid btw (using it without turbo also throws an error but it is less informative)
![image](https://github.com/hashicorp/next-mdx-remote/assets/53496941/c472fc11-0655-4c5e-948d-f201362f232b)

**Comment by dstaley** [comment]
I think this might be a result of `next-mdx-remote` being ESM only. While I investigate whether that's the case you should be able to work around this issue by adding `transpilePackages: ["next-mdx-remote"]` to your `next.config.js`.

**Comment by SuperchupuDev** [comment]
@dstaley I think I finally found out how to solve my problem without adding it to `transpilePackages`. `serialize` isn't meant to be used in the app router, and changing it to just use MDXRemote from `/rsc` solved it. It'd be nice if the examples from the README specified they are meant to be used in the pages router, the info is only really provided [near the bottom of the readme](https://github.com/hashicorp/next-mdx-remote#react-server-components-rsc--nextjs-app-directory-support)
